version: "3.9"

services:
  nginx:
    image: nginx
    restart: always
    ports:
      - "80:80"
  postgres:
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data
  minio:
    image: quay.io/minio/minio:RELEASE.2022-08-05T23-27-09Z
    command: server --console-address ":9001" http://minio/data
    expose:
      - "9000"
      - "9001"
    # environment:
      # MINIO_ROOT_USER: minioadmin
      # MINIO_ROOT_PASSWORD: minioadmin
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3
    volumes:
      - minio-data:/data
  web:
    image: ghcr.io/sadlibrary/web:latest
    depends_on:
      nginx:
      postgres:
      minio:
    environment:
      - DEBUG=true

volumes:
  db-data:
  minio-data: